
- name: Retrieve image by name
  os_image_facts:
    image: "{{ image }}"


- name: Download image if not present
  get_url:
    url: "{{ image_url }}"
    dest: "/tmp/{{ image }}.{{ image_format }}"
  when: (openstack_image is none) or
        (openstack_image.status != "active")


- name: Upload image to Glance
  os_image:
    name: "{{ image }}"
    disk_format: "{{ image_format }}"
    state: present
    filename: "/tmp/{{ image }}.{{ image_format }}"
    properties:
      cpu_arch: "{{ cpu_arch }}"
      distro: "{{ distro }}"
    timeout: "{{ timeout_upload_image }}"
    wait: yes
  when: (openstack_image is none) or
        (openstack_image.status != "active")

