- include_tasks: "{{ provider }}.yml"

# DO NOT DO 'include_vars' from the defaults folder as these will be included with a priority much higher than default variables are supposed to. Instead when including a role, use the statement 'defaults_from'
