- name: Boot new instance
  os_server:
    name: "{{ server }}"
    image: "{{ image }}"
    flavor: "{{ flavor }}"
    state: present
    auto_ip: no  # We do this in the following task
    wait: "{{ wait_for_instance }}"
    security_groups: "{{ sec_groups }}"
    timeout: "{{ timeout_instance_boot }}"
    config_drive: true
    key_name: "{{ keypair }}"
    volumes: "{{ volumes }}"
    network: "{{ private_network }}"
    userdata: |
      #cloud-config
      users:
        - name: {{ username }}
          sudo: ALL=(ALL) NOPASSWD:ALL
          groups: users, admin
          ssh-impot-id: None
          lock_passwd: true
          ssh-authorized-keys: {{ pubkey }}

      packages:
        - ansible
        - make

      package_upgrade: true
  when: server not in (openstack_servers | default([]) | map(attribute='name'))

- name: Sleep before trying to add floating ip
  wait_for:
    timeout: "{{ timeout_before_floating_ip }}"
  delegate_to: localhost
  when: timeout_before_floating_ip != None

- set_fact:
    floatingIp: "{{ openstack_servers | default([]) | json_query(\"[?name=='\" + server + \"'].accessIPv4\") }}"

- debug:
    var: floatingIp

- name: Add floating ip to instance - reuse floating ip or create new one
  os_floating_ip:
    state: present
    reuse: yes
    server: "{{ server }}"
    network: "{{ external_network }}"
    wait: "{{ wait_for_floating_ip }}"
    timeout: "{{ timeout_add_floating_ip }}"
  when: (floatingIp | length) == 0 or (floatingIp | first) == ""
  ignore_errors: yes
